# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
